torweather/__init__.py
#!/usr/bin/env python
from torweather.backend.email import Email
from torweather.backend.relay import Relay
from torweather.exceptions import EmailSendError
from torweather.exceptions import InvalidFingerprintError
from torweather.exceptions import NotifNotSubscribedError
from torweather.exceptions import RelayNotSubscribedError
from torweather.exceptions import RelaySubscribedError
from torweather.schemas import Notif
from torweather.schemas import RelayData

torweather/app.py
#!/usr/bin/env python
"""Module for creating and running flask server."""
import os

from flask import Flask
from flask import render_template

from torweather.backend.check import Check
from torweather.backend.database import Database
from torweather.routes.subscribe import subscribe
from torweather.routes.unsubscribe import unsubscribe

app = Flask(__name__)
app.secret_key = os.urandom(24)
Check().scheduler.start()


@app.route("/")
@app.route("/about")
def home():
    return render_template("about.html")


@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@app.errorhandler(500)
def internal_server_error(e):
    return render_template("500.html"), 500


if __name__ == "__main__":
    app.register_blueprint(subscribe, url_prefix="/subscribe")
    app.register_blueprint(unsubscribe, url_prefix="/unsubscribe")
    port = int(os.environ.get("PORT", 5000))
    # app.run(debug=True)
    Database()  # Setup the tables in torweather database.
    app.run(host="0.0.0.0", port=port)

torweather/routes/subscribe.py
#!/usr/bin/env python
"""Module for handling the "/subscribe" endpoint of flask server."""
from collections.abc import Sequence

from flask import Blueprint
from flask import render_template
from flask import request

from torweather.backend.relay import Relay
from torweather.exceptions import InvalidEmailError
from torweather.exceptions import InvalidFingerprintError
from torweather.schemas import Notif

subscribe = Blueprint("subscribe", __name__)


@subscribe.route("/", methods=["GET", "POST"], strict_slashes=False)
def main():
    """Returns rendered "subscribe.html" template according to constraints."""
    if request.method == "POST":
        email: str = request.form.get("email")
        fingerprint: str = request.form.get("fingerprint")
        node_down: str = request.form.get("node-down")
        outdated_ver: str = request.form.get("outdated-ver")
        duration: int = (
            int(request.form.get("duration"))
            if request.form.get("duration") != ""
            else 48
        )
        duration_type: str = request.form.get("duration-type")
        notifs: Sequence[Notif] = []
        if node_down == "on":
            notifs.append(Notif.NODE_DOWN)
            if duration_type == "days":
                duration *= 24
            elif duration_type == "weeks":
                duration *= 7 * 24
            elif duration_type == "months":
                duration *= 30 * 24
        if outdated_ver == "on":
            notifs.append(Notif.OUTDATED_VER)
        try:
            if not notifs:
                return render_template(
                    "subscribe.html",
                    error="Choose at least one notification to subscribe.",
                )
            relay = Relay(fingerprint)
            result: bool = relay.subscribe(email, notifs, duration)
            if result:
                return render_template(
                    "subscribe.html",
                    subscribed=True,
                    nickname=relay.data.nickname,
                    fingerprint=fingerprint,
                )
            else:
                return render_template(
                    "subscribe.html",
                    subscribed=False,
                    nickname=relay.data.nickname,
                    fingerprint=fingerprint,
                )
        except InvalidEmailError:
            return render_template("subscribe.html", error="Not a valid email address.")
        except InvalidFingerprintError:
            return render_template(
                "subscribe.html", error="Not a valid relay fingerprint."
            )
    return render_template("subscribe.html")

torweather/routes/unsubscribe.py
#!/usr/bin/env python
"""Module for handling the "/unsubscribe" endpoint of flask server."""
import os

from bs4 import BeautifulSoup
from flask import Blueprint
from flask import render_template
from flask import request

from torweather.backend.relay import Relay
from torweather.exceptions import InvalidEmailError
from torweather.exceptions import InvalidFingerprintError
from torweather.exceptions import NotifNotSubscribedError
from torweather.exceptions import RelayNotSubscribedError
from torweather.schemas import Notif

unsubscribe = Blueprint("unsubscribe", __name__)


@unsubscribe.route("/", methods=["GET", "POST"], strict_slashes=False)
def main():
    """Returns rendered "unsubscribe.html" template according to constraints."""
    if request.method == "POST":
        fingerprint: str = request.form.get("fingerprint")
        email: str = request.form.get("email")
        notif_type: str = request.form.get("unsubscribe-notifs")
        try:
            relay = Relay(fingerprint)
            if email != relay.email:
                return render_template(
                    "unsubscribe.html", error="Email not subscribed by relay."
                )
            if notif_type == "all":
                result: bool = relay.unsubscribe()
                if result:
                    return render_template(
                        "unsubscribe.html",
                        unsubscribed=True,
                        nickname=relay.data.nickname,
                        fingerprint=fingerprint,
                    )
            else:
                notif: Notif = getattr(Notif, notif_type.replace("-", "_").upper())
                result: bool = relay.unsubscribe_single(notif)  # type: ignore
                if result:
                    current_directory: str = os.path.dirname(os.path.realpath(__file__))
                    parent_directory: str = os.path.dirname(current_directory)
                    with open(
                        os.path.join(parent_directory, "templates", "unsubscribe.html")
                    ) as file:
                        page_data: str = file.read()
                    # Use BeautifulSoup to get the name of the single notification
                    # that was unsubscribed.
                    soup = BeautifulSoup(page_data, features="lxml")
                    return render_template(
                        "unsubscribe.html",
                        unsubscribed=True,
                        nickname=relay.data.nickname,
                        fingerprint=fingerprint,
                        single=True,
                        notif=soup.find("option", value=notif_type).text,
                    )
        except InvalidEmailError:
            return render_template(
                "unsubscribe.html", error="Not a valid email address."
            )
        except InvalidFingerprintError:
            return render_template(
                "unsubscribe.html", error="Not a valid relay fingerprint."
            )
        except RelayNotSubscribedError:
            return render_template(
                "unsubscribe.html",
                unsubscribed=False,
                nickname=relay.data.nickname,
                fingerprint=fingerprint,
            )
        except NotifNotSubscribedError:
            return render_template(
                "unsubscribe.html", error=f"Chosen notification not subscribed."
            )
    return render_template("unsubscribe.html")

torweather/templates/about.html
{% extends "base.html" %}
{% block title %}Tor Weather - About{% endblock %}
{% block content %}
<h2>What is Tor Weather?</h2>
<p>Tor Weather provides an email notification service to any users who want to monitor the status of a Tor node. Upon subscribing, you can specify what types of alerts you would like to receive. The main purpose of Tor Weather is to notify node operators via email if their node is down for longer than a specified period, but other notification types are available.</p>
<h2>Why should I subscribe?</h2>
<p>Tor Weather is useful to node operators who want to know as soon as their router is down in order to fix the problem.</p>
<h2>Will I be spammed by Tor Weather reports?</h2>
<p>No, you can change your preferences to minimize your Tor Weather email notifications. You can unsubscribe at any time.</p>
{% endblock %}

torweather/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
        <script src="{{ url_for('static', filename='torweather.js') }}"></script>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <header>
            <nav class="main-nav">
                <a href="{{ url_for('home') }}">
                    <img class="logo" src="{{ url_for('static', filename='img/logo.png') }}" height="48">
                </a>
            </nav>
        </header>
        <nav class="side-nav">
            <ul class="side-nav-ul">
                <li class="side-nav-li">
                    <a href="{{ url_for('home') }}">About</a>
                </li>
                <li class="side-nav-li">
                    <a href="{{ url_for('subscribe.main') }}">Subscribe</a>
                </li>
                <li class="side-nav-li">
                    <a href="{{ url_for('unsubscribe.main') }}">Unsubscribe</a>
                </li>
            </ul>
        </nav>
        <div class="main-content">
            <h1>Tor Weather</h1>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

torweather/templates/subscribe.html
{% extends "base.html" %}
{% block title %}Tor Weather - Subscribe{% endblock %}
{% block content %}
<form name="check" action="/subscribe" method="POST" onsubmit="validate()">
    <label for="email">Email:</label>
    <input type="email" name="email" size="30">
    &nbsp;
    <label for="fingerprint">Relay fingerprint:</label>
    <input type="text" name="fingerprint" size="30">
    <br><br>
    <input type="checkbox" name="node-down" checked>
    <label for="node-down">Email me when my relay is down</label>
    <br>
    <label for="duration" class="duration">How long before we send a notification?</label>
    <br>
    <input type="number" name="duration" min="1" max="4380" placeholder="Default value is 48">
    <select name="duration-type">
        <option value="hours" selected>Hours</option>
        <option value="days">Days</option>
        <option value="weeks">Weeks</option>
        <option value="months">Months</option>
    </select>
    <br>
    <input type="checkbox" name="outdated-ver">
    <label for="outdated-ver">Email me when my relay runs an outdated Tor version</label>
    <br>
    <input type="checkbox" name="select-all" onclick="toggleAll(this)">
    <label for="select-all">Subscribe to all notifications</label>
    <br><br>
    <button type="submit">Subscribe</button>
    <br>
</form>
<br>
{% if subscribed == True %}
    <i class="fa-solid fa-check"></i>&nbsp;
    Relay <strong>{{ nickname }}</strong> (fingerprint: {{ fingerprint }}) successfully subscribed to Tor weather service.
{% elif subscribed == False %}
    <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;
    Relay <strong>{{ nickname }}</strong> (fingerprint: {{ fingerprint }}) has already subscribed to Tor weather service.
{% endif %}
{% if error %}
    <i class="fa-solid fa-xmark"></i>&nbsp;
    {{ error }}
{% endif %}
{% endblock %}

torweather/templates/unsubscribe.html
{% extends "base.html" %}
{% block title %}Tor Weather - Unsubscribe{% endblock %}
{% block content %}
<form name="check" action="/unsubscribe" method="POST" onsubmit="validate()">
    <label for="fingerprint">Relay fingerprint:</label>
    <input type="text" name="fingerprint" size="30">
    &nbsp;
    <label for="email">Confirm Email:</label>
    <input type="email" name="email" size="30">
    <br><br>
    <label for="unsubscribe-notifs">Notifications to unsubscribe:&nbsp;</label>
    <select name="unsubscribe-notifs">
        <option value="all" selected>All</option>
        <option value="node-down">Node down</option>
        <option value="outdated-ver">Outdated Tor version</option>
    </select>
    <br><br>
    <button type="submit">Unsubscribe</button>
</form>
<br>
{% if unsubscribed == True %}
    {% if single == True %}
        <i class="fa-solid fa-check"></i>&nbsp;
        Relay <strong>{{ nickname }}</strong> (fingerprint: {{ fingerprint }}) successfully unsubscribed <strong>{{ notif }}</strong> notification.
    {% else %}
        <i class="fa-solid fa-check"></i>&nbsp;
        Relay <strong>{{ nickname }}</strong> (fingerprint: {{ fingerprint }}) successfully unsubscribed from Tor weather service.
    {% endif %}
{% elif unsubscribed == False %}
    <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;
    Relay <strong>{{ nickname }}</strong> (fingerprint: {{ fingerprint }}) has not subscribed to Tor weather service.
{% endif %}
{% if error %}
    <i class="fa-solid fa-xmark"></i>&nbsp;
    {{ error }}
{% endif %}
{% endblock %}